# Generated by Django 4.0.3 on 2022-03-31 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('profile_pic', models.ImageField(default='default.png', upload_to='images/')),
                ('bio', models.CharField(max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('ingredient', models.TextField()),
                ('category', models.CharField(max_length=120)),
                ('recipe_pic', models.ImageField(upload_to='images')),
                ('country', models.CharField(max_length=50)),
                ('procedure', models.TextField(verbose_name='Instructions')),
                ('guests_served', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(verbose_name='Date Created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeapp.profile')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeapp.rating')),
            ],
        ),
    ]
